print("**Students Details**")
rollno=input("Enter your roll no : ")
print("You have entered : ",rollno)
firstname=input("Enter your firstname : ")
print("You have entered : ",firstname)
lastname=input("Enter your lastname : ")
print("You have entered : ",lastname)
phoneno=input("Enter your phone no : ")
print("You have entered : ",phoneno)
address=input("Enter your address : ")
print("You have entered : ",address)
marks=input("Enter your marks : ")
print("You have entered  ",marks)
